### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u4fdd' in position 26: character maps to <undefined>

### ISSUE THREAD

**Issue by Kozlov-AE** [usoonees/logseq-whisper-subtitles-server#5]
I attempted to transcribe a Russian-language video that is over 40 minutes long. 
I had one warning before:
C:\Python311\Lib\site-packages\whisper\transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

Upon completion of the process, I received the following server error:
Traceback (most recent call last):
  File "MyPath\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\app.py", line 74, in transcribe
    "segments": transcribe_audio(audio_path, min_length, model_size, zh_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "MyPath\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\services.py", line 86, in transcribe_audio
    transcribe = model.transcribe(audio=audio_path, verbose=True, initial_prompt="\u5bf9\u4e8e\u666e\u901a\u8bdd\u53e5\u5b50\uff0c\u4ee5\u4e2d\u6587\u7b80\u4f53\u8f93\u51fa")  # \u907f\u514d\u7e41\u4f53\u8f93\u51fa
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\whisper\transcribe.py", line 466, in transcribe
    print(make_safe(line))
  File "C:\Python311\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u4fdd' in position 26: character maps to <undefined>
127.0.0.1 - - [01/Mar/2024 13:10:34] "POST /transcribe HTTP/1.1" 200 -

**Comment by Kozlov-AE** [comment]
I've fixed it with added `.encode("utf-8")`
![image](https://github.com/usoonees/logseq-whisper-subtitles-server/assets/53231526/2eef6dfb-5c47-4270-8f24-2ffbf0ca5a28)
